### ISSUE TITLE
Example not working ?

### ISSUE THREAD

**Issue by julien9999** [vijaysingh-axway/ti.cameraview#2]
Hi @hansemannn, 
Do you mind checking the example and maybe publishing the compiled module to make it work?
Thanks

**Comment by AppWerft** [comment]
Same. On log:
`invalid method (createCamera) passed to TiCameraviewModule";`
in line 55 I see a createCamera method, but the open method is method of module not of result of createCamera. A lot of questions...

**Comment by vijaysingh-axway** [comment]
@julien9999 @AppWerft  Issue resolved. You can check now :)

**Comment by julien9999** [comment]
thanks @vijaysingh-axway 
Maybe you could also add the example ?
Thanks
